godot_repository_executable := "godot"
godot_executable := env_var_or_default("GODOT", godot_repository_executable)

import:
    "{{godot_executable}}" --path . --headless --import --quit

test test_path:
    "{{godot_executable}}" --path . --headless -s addons/gut/gut_cmdln.gd -gtest={{test_path}} -gexit

test-all:
    "{{godot_executable}}" --path . --headless -s addons/gut/gut_cmdln.gd -gdir=res://tests -gexit

runtime:
    "{{godot_executable}}" --path . --headless -s tests/verify_runtime.gd

validate: import test-all runtime
